version: '3.4'

services:
  identity.db:
    container_name: identity.db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2283221488
      POSTGRES_USER: identity_db_user
      POSTGRES_DB: identity_db
    volumes:
      - ./identity-db-data:/var/lib/postgresql/data
      - ./init-identity-db:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
      
  application.server.db:
    container_name: web.server.db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 2283221488
      POSTGRES_USER: web_server_db_user
      POSTGRES_DB: web_server_db
    volumes:
      - ./web-server-db-data:/var/lib/postgresql/data
      - ./init-web-server-db:/docker-entrypoint-initdb.d
    ports:
      - "5434:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    restart: always
    ports:
      - '5050:80'
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin